include --> INVALID IDENTIFIER [RESERVED KEYWORDS]
iostream --> IDENTIFIER
include --> INVALID IDENTIFIER [RESERVED KEYWORDS]
map --> IDENTIFIER
include --> INVALID IDENTIFIER [RESERVED KEYWORDS]
sstream --> IDENTIFIER
include --> INVALID IDENTIFIER [RESERVED KEYWORDS]
string --> IDENTIFIER
include --> INVALID IDENTIFIER [RESERVED KEYWORDS]
vector --> IDENTIFIER
using --> IDENTIFIER
namespace --> IDENTIFIER
std --> IDENTIFIER
/*

main function 
and 
other 
utilities

blah
blaaah
blaaaaahhhhh

hello
ehllo
heoll
olleh
helll


*/ --> COMMENT
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
main --> IDENTIFIER
//main function --> COMMENT
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
t --> IDENTIFIER
_states --> IDENTIFIER
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
t --> IDENTIFIER
_in --> IDENTIFIER
_sym --> IDENTIFIER
string --> IDENTIFIER
s --> IDENTIFIER
Real --> IDENTIFIER
Number --> IDENTIFIER
1.75e-30 --> REAL NUMBER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Total --> IDENTIFIER
States --> IDENTIFIER
//test line --> COMMENT
cin --> IDENTIFIER
t --> IDENTIFIER
_states --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Total --> IDENTIFIER
Input --> IDENTIFIER
symbols --> IDENTIFIER
cin --> IDENTIFIER
t --> IDENTIFIER
_in --> IDENTIFIER
_sym --> IDENTIFIER
string --> IDENTIFIER
states --> IDENTIFIER
string --> IDENTIFIER
in --> IDENTIFIER
_symbols --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
All --> IDENTIFIER
the --> IDENTIFIER
states --> IDENTIFIER
as --> IDENTIFIER
a --> IDENTIFIER
string --> IDENTIFIER
cin --> IDENTIFIER
states --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
all --> IDENTIFIER
the --> IDENTIFIER
input --> IDENTIFIER
symbol --> IDENTIFIER
as --> IDENTIFIER
a --> IDENTIFIER
string --> IDENTIFIER
cin --> IDENTIFIER
in --> IDENTIFIER
_symbols --> IDENTIFIER
char --> IDENTIFIER
space --> IDENTIFIER
_char --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
character --> IDENTIFIER
for --> IDENTIFIER
space --> IDENTIFIER
cin --> IDENTIFIER
space --> IDENTIFIER
_char --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
STATE --> IDENTIFIER
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
IN --> IDENTIFIER
_SYMBOL --> IDENTIFIER
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
TRANSITION --> IDENTIFIER
VALUE --> IDENTIFIER
n --> IDENTIFIER
char --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
//temp char --> COMMENT
string --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
stringstream --> IDENTIFIER
ss --> IDENTIFIER
map --> IDENTIFIER
string --> IDENTIFIER
char --> IDENTIFIER
sparse --> IDENTIFIER
_matrix --> IDENTIFIER
for --> IDENTIFIER
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
i --> IDENTIFIER
0 --> INTEGER
i --> IDENTIFIER
states --> IDENTIFIER
length --> IDENTIFIER
i --> IDENTIFIER
+ --> OPERATOR
+ --> OPERATOR
for --> IDENTIFIER
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
j --> IDENTIFIER
0 --> INTEGER
j --> IDENTIFIER
in --> IDENTIFIER
_symbols --> IDENTIFIER
length --> IDENTIFIER
+ --> OPERATOR
+ --> OPERATOR
j --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
states --> IDENTIFIER
i --> IDENTIFIER
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
in --> IDENTIFIER
_symbols --> IDENTIFIER
j --> IDENTIFIER
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
cin --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
if --> INVALID IDENTIFIER [RESERVED KEYWORDS]
temp --> IDENTIFIER
_char --> IDENTIFIER
space --> IDENTIFIER
_char --> IDENTIFIER
/*
					new comment line
					is present
					here
				*/ --> COMMENT
ss --> IDENTIFIER
states --> IDENTIFIER
i --> IDENTIFIER
in --> IDENTIFIER
_symbols --> IDENTIFIER
j --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
ss --> IDENTIFIER
str --> IDENTIFIER
sparse --> IDENTIFIER
_matrix --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
STATE --> IDENTIFIER
INSERTED --> IDENTIFIER
n --> IDENTIFIER
else --> INVALID IDENTIFIER [RESERVED KEYWORDS]
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
STATE --> IDENTIFIER
NOT --> IDENTIFIER
INSERTED --> IDENTIFIER
n --> IDENTIFIER
continue --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
the --> IDENTIFIER
initial --> IDENTIFIER
states --> IDENTIFIER
as --> IDENTIFIER
a --> IDENTIFIER
string --> IDENTIFIER
cin --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
vector --> IDENTIFIER
char --> IDENTIFIER
ini --> IDENTIFIER
_states --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
begin --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
end --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
the --> IDENTIFIER
accepting --> IDENTIFIER
states --> IDENTIFIER
as --> IDENTIFIER
a --> IDENTIFIER
string --> IDENTIFIER
cin --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
vector --> IDENTIFIER
char --> IDENTIFIER
acp --> IDENTIFIER
_states --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
begin --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
end --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
your --> IDENTIFIER
starting --> IDENTIFIER
state --> IDENTIFIER
cin --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
char --> IDENTIFIER
prev --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
char --> IDENTIFIER
curr --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
prev --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
Enter --> IDENTIFIER
the --> IDENTIFIER
input --> IDENTIFIER
string --> IDENTIFIER
cin --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
vector --> IDENTIFIER
char --> IDENTIFIER
input --> IDENTIFIER
_str --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
begin --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
end --> IDENTIFIER
bool --> IDENTIFIER
accepting --> IDENTIFIER
_state --> IDENTIFIER
bool --> IDENTIFIER
accepted --> IDENTIFIER
for --> IDENTIFIER
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
i --> IDENTIFIER
0 --> INTEGER
i --> IDENTIFIER
input --> IDENTIFIER
_str --> IDENTIFIER
size --> IDENTIFIER
i --> IDENTIFIER
+ --> OPERATOR
+ --> OPERATOR
prev --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
curr --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
accepting --> IDENTIFIER
_state --> IDENTIFIER
false --> IDENTIFIER
accepted --> IDENTIFIER
false --> IDENTIFIER
ss --> IDENTIFIER
prev --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
input --> IDENTIFIER
_str --> IDENTIFIER
i --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
ss --> IDENTIFIER
str --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
sparse --> IDENTIFIER
_matrix --> IDENTIFIER
temp --> IDENTIFIER
_str --> IDENTIFIER
for --> IDENTIFIER
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
j --> IDENTIFIER
0 --> INTEGER
j --> IDENTIFIER
t --> IDENTIFIER
_states --> IDENTIFIER
j --> IDENTIFIER
+ --> OPERATOR
+ --> OPERATOR
if --> INVALID IDENTIFIER [RESERVED KEYWORDS]
temp --> IDENTIFIER
_char --> IDENTIFIER
states --> IDENTIFIER
j --> IDENTIFIER
accepted --> IDENTIFIER
true --> IDENTIFIER
if --> INVALID IDENTIFIER [RESERVED KEYWORDS]
accepted --> IDENTIFIER
curr --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
temp --> IDENTIFIER
_char --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
prev --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
curr --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
for --> IDENTIFIER
int --> INVALID IDENTIFIER [RESERVED KEYWORDS]
k --> IDENTIFIER
0 --> INTEGER
k --> IDENTIFIER
acp --> IDENTIFIER
_states --> IDENTIFIER
size --> IDENTIFIER
k --> IDENTIFIER
+ --> OPERATOR
+ --> OPERATOR
if --> INVALID IDENTIFIER [RESERVED KEYWORDS]
acp --> IDENTIFIER
_states --> IDENTIFIER
k --> IDENTIFIER
curr --> IDENTIFIER
_in --> IDENTIFIER
_str --> IDENTIFIER
_char --> IDENTIFIER
accepting --> IDENTIFIER
_state --> IDENTIFIER
true --> IDENTIFIER
if --> INVALID IDENTIFIER [RESERVED KEYWORDS]
accepting --> IDENTIFIER
_state --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
- --> OPERATOR
ACCEPTING --> IDENTIFIER
STATE --> IDENTIFIER
n --> IDENTIFIER
else --> INVALID IDENTIFIER [RESERVED KEYWORDS]
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
endl --> IDENTIFIER
else --> INVALID IDENTIFIER [RESERVED KEYWORDS]
break --> IDENTIFIER
if --> INVALID IDENTIFIER [RESERVED KEYWORDS]
accepting --> IDENTIFIER
_state --> IDENTIFIER
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
nInput --> IDENTIFIER
String --> IDENTIFIER
is --> IDENTIFIER
acceptable --> IDENTIFIER
n --> IDENTIFIER
else --> INVALID IDENTIFIER [RESERVED KEYWORDS]
cout --> INVALID IDENTIFIER [RESERVED KEYWORDS]
nInput --> IDENTIFIER
String --> IDENTIFIER
is --> IDENTIFIER
NOT --> IDENTIFIER
acceptable --> IDENTIFIER
n --> IDENTIFIER
return --> INVALID IDENTIFIER [RESERVED KEYWORDS]
0 --> INTEGER
